# Generated by Django 2.2 on 2020-09-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('resources', '0001_initial'), ('resources', '0002_auto_20200911_1004')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PktTrailResource',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('res_type', models.IntegerField(default=0)),
                ('agent_url', models.URLField()),
                ('data_url', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(blank=True, max_length=512, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pkt_trail_resources',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PktTrailService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('proto', models.CharField(blank=True, max_length=8)),
                ('port_no', models.IntegerField()),
                ('filter_str', models.CharField(blank=True, max_length=64)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='resources.PktTrailResource')),
            ],
            options={
                'db_table': 'pkt_trail_services',
            },
        ),
    ]
