# Generated by Django 2.2 on 2020-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_squashed_0002_auto_20200911_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pkttrailservice',
            old_name='port_no',
            new_name='port',
        ),
        migrations.AddField(
            model_name='pkttrailservice',
            name='interface',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='pkttrailservice',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Running'), (1, 'Stopped'), (2, 'Error')], default=-1),
        ),
        migrations.AlterField(
            model_name='pkttrailresource',
            name='res_type',
            field=models.IntegerField(choices=[(0, 'VM/Os'), (1, 'k8s')], default=0),
        ),
        migrations.AlterField(
            model_name='pkttrailresource',
            name='state',
            field=models.IntegerField(choices=[(0, 'Provisioned'), (1, 'Offline'), (2, 'Online'), (3, 'Capture Active'), (4, 'Error')], default=0),
        ),
    ]
